name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2 via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/app"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update & install Docker & Docker Compose plugin
          sudo apt update
          sudo apt install -y docker.io
          sudo apt install -y docker-compose-plugin

          # Start Docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Add user to docker group (so you don't need to use sudo for docker commands)
          sudo usermod -aG docker $USER || true
          newgrp docker || true

          # Verify Docker Compose installation
          docker compose version

          # Deploy the app
          cd ~/app
          docker compose down || true
          docker compose up --build -d
